"""Added backup_media column

Revision ID: 0ce71094ce47
Revises: 6e8db52cd70f
Create Date: 2025-03-03 11:56:21.464225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce71094ce47'
down_revision = '6e8db52cd70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_media', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_record', schema=None) as batch_op:
        batch_op.drop_column('backup_media')

    # ### end Alembic commands ###
