"""Initial migration

Revision ID: 6e8db52cd70f
Revises: 4bcf856e1a76
Create Date: 2025-03-03 05:36:53.006786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8db52cd70f'
down_revision = '4bcf856e1a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_record', schema=None) as batch_op:
        batch_op.alter_column('backup_frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('tape_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('backup_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('server',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('os',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('backup_contents',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('backup_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('backup_media')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_media', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('backup_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('backup_contents',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('os',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('server',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('backup_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('tape_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('backup_frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
